name: pdf_scanner
description: "Scanner to pdf"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  pdf: ^3.11.0
  open_file: ^3.3.2
  extended_image: ^8.2.1
  image_cropper: ^7.1.0
  intl: ^0.19.0
  share_plus: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
